=== crdpacversailles/glup-web/langues/xmldoctype.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT language (xmldata*) >	
	<!ELEMENT xmldata (translation+) >
	<!ATTLIST xmldata id ID #REQUIRED >
		<!ELEMENT translation (#PCDATA) >
		<!ATTLIST translation lang CDATA #REQUIRED >

=== crdpacversailles/glup-web/XMLEngine/xml/website.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "xmldoctype.dtd">
<language>
	<xmldata id="inputID">
		<translation lang="fr">ID de la balise</translation>
		<translation lang="en-gb">Tag's ID</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="inputData">
		<translation lang="fr">Données de la balise</translation>
		<translation lang="en-gb">Tag's datas</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="frLang">
		<translation lang="fr">Français</translation>
		<translation lang="en-gb">French</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="en-gbLang">
		<translation lang="fr">Anglais</translation>
		<translation lang="en-gb">English</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="deLang">
		<translation lang="fr">Allemand</translation>
		<translation lang="en-gb">German</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="submitModify">
		<translation lang="fr">Modifier un élément</translation>
		<translation lang="en-gb">Modify tag</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="submitCreate">
		<translation lang="fr">Créer un nouvel élément</translation>
		<translation lang="en-gb">Create new tag</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="inputLang">
		<translation lang="fr">Choix de la langue</translation>
		<translation lang="en-gb">Choose language</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="modifyXmlDone">
		<translation lang="fr">Les modifications ont été effectuées !</translation>
		<translation lang="en-gb">Modifications saved successfully !</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="modifyXmlError">
		<translation lang="fr">Erreur detectée ! Aucune sauvegarde faite.</translation>
		<translation lang="en-gb">Error detected ! No save.</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="createXmlDone">
		<translation lang="fr">Elément créer !</translation>
		<translation lang="en-gb">New tag created !</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="createXmlError">
		<translation lang="fr">Erreur ! L'élément existe sûrement.</translation>
		<translation lang="en-gb">Error ! Existant tag.</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="newContent">
		<translation lang="fr">Nouvelle valeur</translation>
		<translation lang="en-gb">New data</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="submitTraduce">
		<translation lang="fr">Effectuer la traduction</translation>
		<translation lang="en-gb">Make translation</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="foreignLang">
		<translation lang="fr">Langue de traduction</translation>
		<translation lang="en-gb">Language to traduce</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="submitChooseLang">
		<translation lang="fr">Choisir cette langue</translation>
		<translation lang="en-gb">Choose this language</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="modificationDone">
		<translation lang="fr">Les modifications sont sauvées !</translation>
		<translation lang="en-gb">Modification saved!</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="modificationError">
		<translation lang="fr">Une erreur s'est produite ! Prévenez le webmaster</translation>
		<translation lang="en-gb">Error occured ! Contact the webmaster</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="element">
		<translation lang="fr">Elément</translation>
		<translation lang="en-gb">Element</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="deleteElement">
		<translation lang="fr">Supprimer cet élément</translation>
		<translation lang="en-gb">Delete this element</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="confirmDelete">
		<translation lang="fr">Voulez-vous supprimer l'élément</translation>
		<translation lang="en-gb">Do you want to delete this element</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="webPageName">
		<translation lang="fr">Démonstration de XMLEngine</translation>
		<translation lang="en-gb">XMLEngin demonstration</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="languageToCheck">
		<translation lang="fr">Langue(s) à vérifier</translation>
		<translation lang="en-gb">Languages to check</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="checkIt">
		<translation lang="fr">Vérifier</translation>
		<translation lang="en-gb">Check</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="checkLanguageDone">
		<translation lang="fr">La langue est désormais accessible pour les utilisateurs !</translation>
		<translation lang="en-gb">This language is available</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="fileCheckError">
		<translation lang="fr">Le fichier suivant comprend des erreurs</translation>
		<translation lang="en-gb">This file have somes error</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="TITRE">
		<translation lang="fr">Générateur ludopédagogique du CRDP de l'Académie de versailles</translation>
		<translation lang="en-gb">Educational serious game builder of the CRDP of the Versailles Academy</translation>
		<translation lang="de">Spass-pädagogische Generator der CRDP der Académie de Versailles</translation>
	</xmldata>
	<xmldata id="ACCUEIL">
		<translation lang="fr">Accueil</translation>
		<translation lang="en-gb">Home</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="SAVOIR">
		<translation lang="fr">En savoir plus</translation>
		<translation lang="en-gb">Learn more</translation>
		<translation lang="de">Mehr wissen</translation>
	</xmldata>
	<xmldata id="TESTER">
		<translation lang="fr">Tester Glup</translation>
		<translation lang="en-gb">Try it</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="CONTRIBUER">
		<translation lang="fr">Contribuer</translation>
		<translation lang="en-gb">Contribute</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-BANDEAU">
		<translation lang="fr">VERSION PROTOTYPE</translation>
		<translation lang="en-gb">PROTOTYPE VERSION</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-PUCE-PRESENTATION">
		<translation lang="fr">Glup est un service en ligne qui vous permet de transformer vos exercices à base de texte en mini-jeux  téléchargeables</translation>
		<translation lang="en-gb">Glup is an online service that lets you turn your text-based exercises into downloadable mini-games</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-PUCE-TEST">
		<translation lang="fr">Cette version de Glup vous propose déjà un type d’exercice et deux mini-jeux</translation>
		<translation lang="en-gb">This version of Glup already offers a type of exercise and two mini-games</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-PUCE-CONTRIBUTION">
		<translation lang="fr"> Pour mettre au point l’application définitive, vos contributions seront précieuses: suggestions de mini-jeux, signalement de bugs…</translation>
		<translation lang="en-gb">To develop the final application, your contributions will be invaluable: suggestions of mini-games, bugs report...</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-LIEN-PRESENTATION">
		<translation lang="fr">en savoir plus</translation>
		<translation lang="en-gb">learn more</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-LIEN-TEST">
		<translation lang="fr">tester glup</translation>
		<translation lang="en-gb">try it.</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="ACCUEIL-LIEN-CONTRIBUTION">
		<translation lang="fr">contribuer</translation>
		<translation lang="en-gb">contribute</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-DEMARRAGE">
		<translation lang="fr">Démarrer</translation>
		<translation lang="en-gb">Start</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-CHOIX-PEDAGO">
		<translation lang="fr">1. Principe pédagogique</translation>
		<translation lang="en-gb">1. Pedagogical principle</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-CONTENU">
		<translation lang="fr">2. Contenu</translation>
		<translation lang="en-gb">2. Content</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-CHOIX-LUDIQUE">
		<translation lang="fr">3. Principe ludique</translation>
		<translation lang="en-gb">3. Gameplay</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-OPTIONS">
		<translation lang="fr">4. Options</translation>
		<translation lang="en-gb">4. Options</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-MODE-EMPLOI">
		<translation lang="fr">5. Mode d'emploi</translation>
		<translation lang="en-gb">5. Game instructions</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="MENU-TEST-EXPORT">
		<translation lang="fr">6. Exporter le jeu</translation>
		<translation lang="en-gb">6. Export game</translation>
		<translation lang="de">
		</translation>
	</xmldata>
	<xmldata id="TEST-DEMARRAGE-TITRE">
